/*
Description: Given a start Person, find Tags that are attached to Posts that were created by that Person’s
friends. Only include Tags that were attached to friends’ Posts created within a given time interval, and that
were never attached to friends’ Posts created before this interval.
*/

PREFIX snvoc: <http://www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?tagName (COUNT(?tagName) AS ?count)
WHERE
{
?person snvoc:id "13194139533332"^^xsd:long ;
	 rdf:type snvoc:Person .

?person (snvoc:knows/snvoc:hasPerson) ?friend .

?post snvoc:hasCreator ?friend ; 
	rdf:type snvoc:Post ;
	snvoc:creationDate ?date ;
	snvoc:hasTag ?tag .

?tag foaf:name ?tagName .

FILTER(?date < "2011-09-28T20:00:00.123+02:00"^^xsd:dateTime)
FILTER(?date > "2009-01-01T19:00:00.123+01:00"^^xsd:dateTime)
}
GROUP BY ?tagName
ORDER BY DESC(?count) ASC(?tagName)
LIMIT 10

